import { Migration } from '@mikro-orm/migrations';

export class Migration20251215033553 extends Migration {

  override async up(): Promise<void> {
    this.addSql(`create table "audit_logs" ("id" uuid not null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "tenant_id" varchar(255) null, "action" varchar(255) not null, "entity_type" varchar(255) not null, "entity_id" varchar(255) null, "actor_id" varchar(255) null, "actor_role" text check ("actor_role" in ('CUSTOMER', 'DRIVER', 'AGENCY_ADMIN', 'DISPATCHER', 'FINANCE', 'SUPER_ADMIN')) not null, "actor_ip" varchar(255) null, "actor_user_agent" varchar(255) null, "changes" jsonb null, "description" text null, "metadata" jsonb null, "timestamp" timestamptz not null, constraint "audit_logs_pkey" primary key ("id"));`);
    this.addSql(`create index "audit_logs_entity_type_entity_id_index" on "audit_logs" ("entity_type", "entity_id");`);
    this.addSql(`create index "audit_logs_actor_id_index" on "audit_logs" ("actor_id");`);
    this.addSql(`create index "audit_logs_tenant_id_action_index" on "audit_logs" ("tenant_id", "action");`);

    this.addSql(`create table "ledger_entries" ("id" uuid not null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "tenant_id" varchar(255) null, "type" text check ("type" in ('TRIP_CHARGE', 'PARCEL_CHARGE', 'COMMISSION', 'DRIVER_EARNING', 'COD_COLLECTED', 'COD_SETTLEMENT', 'REFUND', 'ADJUSTMENT')) not null, "amount" numeric(10,2) not null, "currency" text check ("currency" in ('YER', 'USD')) not null, "fx_rate" numeric(10,6) null, "fx_source" varchar(255) null, "fx_timestamp" timestamptz null, "reporting_amount" numeric(10,2) null, "reporting_currency" text check ("reporting_currency" in ('YER', 'USD')) not null, "debit_account" varchar(255) not null, "credit_account" varchar(255) not null, "related_entity_type" varchar(255) not null, "related_entity_id" varchar(255) not null, "customer_id" varchar(255) null, "driver_id" varchar(255) null, "idempotency_key" varchar(255) not null, "description" text null, "metadata" jsonb null, "transaction_date" timestamptz not null, constraint "ledger_entries_pkey" primary key ("id"));`);
    this.addSql(`create index "ledger_entries_type_index" on "ledger_entries" ("type");`);
    this.addSql(`alter table "ledger_entries" add constraint "ledger_entries_idempotency_key_unique" unique ("idempotency_key");`);
    this.addSql(`create index "ledger_entries_related_entity_type_related_entity_id_index" on "ledger_entries" ("related_entity_type", "related_entity_id");`);
    this.addSql(`create index "ledger_entries_tenant_id_type_index" on "ledger_entries" ("tenant_id", "type");`);

    this.addSql(`create table "pricing_rules" ("id" uuid not null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "tenant_id" varchar(255) null, "name" varchar(255) not null, "name_ar" varchar(255) null, "description" text null, "trip_type" text check ("trip_type" in ('IN_TOWN_TAXI', 'IN_TOWN_SHARED', 'OUT_TOWN_VIP', 'OUT_TOWN_SHARED')) not null, "parcel_size" text check ("parcel_size" in ('SMALL', 'MEDIUM', 'LARGE', 'EXTRA_LARGE')) not null, "from_city" varchar(255) null, "to_city" varchar(255) null, "corridor" varchar(255) null, "base_fare" numeric(10,2) null, "per_km_rate" numeric(10,2) null, "per_minute_rate" numeric(10,2) null, "minimum_fare" numeric(10,2) null, "maximum_fare" numeric(10,2) null, "rush_hour_multiplier" numeric(3,2) null, "vip_multiplier" numeric(3,2) null, "shared_ride_discount" numeric(3,2) null, "rush_hour_windows" jsonb null, "cod_fee_fixed" numeric(10,2) null, "cod_fee_percentage" numeric(5,2) null, "currency" text check ("currency" in ('YER', 'USD')) not null default 'YER', "is_active" boolean not null default true, "valid_from" timestamptz null, "valid_until" timestamptz null, "priority" int not null default 0, "metadata" jsonb null, constraint "pricing_rules_pkey" primary key ("id"));`);
    this.addSql(`create index "pricing_rules_tenant_id_is_active_index" on "pricing_rules" ("tenant_id", "is_active");`);

    this.addSql(`create table "tenants" ("id" uuid not null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "name" varchar(255) not null, "name_ar" varchar(255) null, "description" text null, "slug" varchar(255) not null, "logo_url" varchar(255) null, "contact_email" varchar(255) null, "contact_phone" varchar(255) null, "address" jsonb null, "settings" jsonb null, "is_active" boolean not null default true, constraint "tenants_pkey" primary key ("id"));`);
    this.addSql(`alter table "tenants" add constraint "tenants_name_unique" unique ("name");`);
    this.addSql(`alter table "tenants" add constraint "tenants_slug_unique" unique ("slug");`);

    this.addSql(`create table "drivers" ("id" uuid not null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "tenant_id" uuid not null, "phone" varchar(255) not null, "email" varchar(255) null, "first_name" varchar(255) not null, "last_name" varchar(255) not null, "first_name_ar" varchar(255) null, "last_name_ar" varchar(255) null, "avatar_url" varchar(255) null, "password_hash" varchar(255) null, "refresh_token" varchar(255) null, "device_token" varchar(255) null, "preferred_language" varchar(255) null default 'ar', "kyc_status" text check ("kyc_status" in ('PENDING', 'APPROVED', 'REJECTED')) not null default 'PENDING', "kyc_documents" jsonb null, "kyc_reviewed_by" varchar(255) null, "kyc_reviewed_at" timestamptz null, "kyc_rejection_reason" text null, "vehicle_type" text check ("vehicle_type" in ('SEDAN', 'SUV', 'VAN', 'MINIBUS')) not null, "vehicle_make" varchar(255) not null, "vehicle_model" varchar(255) not null, "vehicle_year" int not null, "vehicle_color" varchar(255) not null, "vehicle_color_ar" varchar(255) null, "vehicle_plate_number" varchar(255) not null, "vehicle_photo_url" varchar(255) null, "vehicle_capacity" int not null default 4, "status" text check ("status" in ('OFFLINE', 'ONLINE', 'BUSY')) not null default 'OFFLINE', "current_location" point null, "current_heading" int null, "last_location_update" timestamptz null, "total_trips" int not null default 0, "total_parcels" int not null default 0, "average_rating" numeric(3,2) not null default 0, "total_ratings" int not null default 0, "is_active" boolean not null default true, "last_login_at" timestamptz null, "metadata" jsonb null, constraint "drivers_pkey" primary key ("id"));`);
    this.addSql(`create index "drivers_kyc_status_index" on "drivers" ("kyc_status");`);
    this.addSql(`create index "drivers_status_index" on "drivers" ("status");`);
    this.addSql(`create index "drivers_status_index" on "drivers" ("status");`);
    this.addSql(`create index "drivers_tenant_id_phone_index" on "drivers" ("tenant_id", "phone");`);

    this.addSql(`create table "users" ("id" uuid not null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "tenant_id" uuid null, "phone" varchar(255) not null, "email" varchar(255) null, "first_name" varchar(255) null, "last_name" varchar(255) null, "first_name_ar" varchar(255) null, "last_name_ar" varchar(255) null, "avatar_url" varchar(255) null, "role" text check ("role" in ('CUSTOMER', 'DRIVER', 'AGENCY_ADMIN', 'DISPATCHER', 'FINANCE', 'SUPER_ADMIN')) not null default 'CUSTOMER', "password_hash" varchar(255) null, "refresh_token" varchar(255) null, "device_token" varchar(255) null, "preferred_language" varchar(255) null default 'ar', "is_phone_verified" boolean not null default false, "phone_verified_at" timestamptz null, "is_id_verified" boolean not null default false, "id_verified_at" timestamptz null, "id_document" jsonb null, "is_active" boolean not null default true, "last_login_at" timestamptz null, "metadata" jsonb null, constraint "users_pkey" primary key ("id"));`);
    this.addSql(`alter table "users" add constraint "users_phone_unique" unique ("phone");`);
    this.addSql(`create index "users_role_index" on "users" ("role");`);
    this.addSql(`create index "users_tenant_id_phone_index" on "users" ("tenant_id", "phone");`);

    this.addSql(`create table "trips" ("id" uuid not null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "tenant_id" uuid not null, "customer_id" uuid not null, "driver_id" uuid null, "type" text check ("type" in ('IN_TOWN_TAXI', 'IN_TOWN_SHARED', 'OUT_TOWN_VIP', 'OUT_TOWN_SHARED')) not null, "status" text check ("status" in ('REQUESTED', 'ASSIGNED', 'DRIVER_ARRIVED', 'STARTED', 'COMPLETED', 'CANCELLED')) not null default 'REQUESTED', "pickup_location" point not null, "pickup_address" jsonb not null, "dropoff_location" point not null, "dropoff_address" jsonb not null, "scheduled_pickup_time" timestamptz null, "is_scheduled" boolean not null default false, "estimated_fare" numeric(10,2) not null, "final_fare" numeric(10,2) null, "currency" text check ("currency" in ('YER', 'USD')) not null default 'YER', "pricing_breakdown" jsonb null, "estimated_distance" numeric(8,2) null, "actual_distance" numeric(8,2) null, "estimated_duration" int null, "actual_duration" int null, "passenger_count" int not null default 1, "shared_ride_group_id" varchar(255) null, "requested_at" timestamptz null, "assigned_at" timestamptz null, "driver_arrived_at" timestamptz null, "started_at" timestamptz null, "completed_at" timestamptz null, "cancelled_at" timestamptz null, "cancellation_reason" text null, "cancelled_by" varchar(255) null, "customer_rating" int null, "customer_review" text null, "driver_rating" int null, "driver_review" text null, "customer_notes" text null, "driver_notes" text null, "metadata" jsonb null, constraint "trips_pkey" primary key ("id"));`);
    this.addSql(`create index "trips_type_index" on "trips" ("type");`);
    this.addSql(`create index "trips_status_index" on "trips" ("status");`);
    this.addSql(`create index "trips_driver_id_index" on "trips" ("driver_id");`);
    this.addSql(`create index "trips_customer_id_index" on "trips" ("customer_id");`);
    this.addSql(`create index "trips_tenant_id_status_index" on "trips" ("tenant_id", "status");`);

    this.addSql(`create table "trip_events" ("id" uuid not null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "trip_id" uuid not null, "status" text check ("status" in ('REQUESTED', 'ASSIGNED', 'DRIVER_ARRIVED', 'STARTED', 'COMPLETED', 'CANCELLED')) not null, "timestamp" timestamptz not null, "location" point null, "notes" text null, "actor_id" varchar(255) null, "actor_role" text check ("actor_role" in ('CUSTOMER', 'DRIVER', 'AGENCY_ADMIN', 'DISPATCHER', 'FINANCE', 'SUPER_ADMIN')) not null, "metadata" jsonb null, constraint "trip_events_pkey" primary key ("id"));`);

    this.addSql(`create table "parcels" ("id" uuid not null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "tenant_id" uuid not null, "sender_id" uuid not null, "receiver_id" uuid null, "receiver_name" varchar(255) not null, "receiver_phone" varchar(255) not null, "driver_id" uuid null, "status" text check ("status" in ('CREATED', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED')) not null default 'CREATED', "size" text check ("size" in ('SMALL', 'MEDIUM', 'LARGE', 'EXTRA_LARGE')) not null, "description" text null, "weight" numeric(8,2) null, "dimensions" jsonb null, "is_fragile" boolean not null default false, "pickup_location" point not null, "pickup_address" jsonb not null, "delivery_location" point not null, "delivery_address" jsonb not null, "delivery_fee" numeric(10,2) not null, "currency" text check ("currency" in ('YER', 'USD')) not null default 'YER', "pricing_breakdown" jsonb null, "is_cod" boolean not null default false, "cod_amount" numeric(10,2) null, "cod_collected" boolean not null default false, "cod_collected_at" timestamptz null, "cod_settled" boolean not null default false, "cod_settled_at" timestamptz null, "pickup_otp" varchar(255) not null, "pickup_otpverified" boolean not null default false, "pickup_otpverified_at" timestamptz null, "delivery_otp" varchar(255) not null, "delivery_otpverified" boolean not null default false, "delivery_otpverified_at" timestamptz null, "pickup_photo_url" varchar(255) null, "pickup_photo_metadata" jsonb null, "delivery_photo_url" varchar(255) null, "delivery_photo_metadata" jsonb null, "assigned_at" timestamptz null, "picked_up_at" timestamptz null, "delivered_at" timestamptz null, "cancelled_at" timestamptz null, "cancellation_reason" text null, "cancelled_by" varchar(255) null, "sender_rating" int null, "sender_review" text null, "sender_notes" text null, "driver_notes" text null, "metadata" jsonb null, constraint "parcels_pkey" primary key ("id"));`);
    this.addSql(`create index "parcels_status_index" on "parcels" ("status");`);
    this.addSql(`create index "parcels_driver_id_index" on "parcels" ("driver_id");`);
    this.addSql(`create index "parcels_receiver_id_index" on "parcels" ("receiver_id");`);
    this.addSql(`create index "parcels_sender_id_index" on "parcels" ("sender_id");`);
    this.addSql(`create index "parcels_tenant_id_status_index" on "parcels" ("tenant_id", "status");`);

    this.addSql(`create table "parcel_events" ("id" uuid not null, "created_at" timestamptz not null, "updated_at" timestamptz not null, "parcel_id" uuid not null, "status" text check ("status" in ('CREATED', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED')) not null, "timestamp" timestamptz not null, "location" point null, "notes" text null, "photo_url" varchar(255) null, "otp_verified" boolean not null default false, "actor_id" varchar(255) null, "actor_role" text check ("actor_role" in ('CUSTOMER', 'DRIVER', 'AGENCY_ADMIN', 'DISPATCHER', 'FINANCE', 'SUPER_ADMIN')) not null, "metadata" jsonb null, constraint "parcel_events_pkey" primary key ("id"));`);

    this.addSql(`alter table "drivers" add constraint "drivers_tenant_id_foreign" foreign key ("tenant_id") references "tenants" ("id") on update cascade;`);

    this.addSql(`alter table "users" add constraint "users_tenant_id_foreign" foreign key ("tenant_id") references "tenants" ("id") on update cascade on delete set null;`);

    this.addSql(`alter table "trips" add constraint "trips_tenant_id_foreign" foreign key ("tenant_id") references "tenants" ("id") on update cascade;`);
    this.addSql(`alter table "trips" add constraint "trips_customer_id_foreign" foreign key ("customer_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "trips" add constraint "trips_driver_id_foreign" foreign key ("driver_id") references "drivers" ("id") on update cascade on delete set null;`);

    this.addSql(`alter table "trip_events" add constraint "trip_events_trip_id_foreign" foreign key ("trip_id") references "trips" ("id") on update cascade;`);

    this.addSql(`alter table "parcels" add constraint "parcels_tenant_id_foreign" foreign key ("tenant_id") references "tenants" ("id") on update cascade;`);
    this.addSql(`alter table "parcels" add constraint "parcels_sender_id_foreign" foreign key ("sender_id") references "users" ("id") on update cascade;`);
    this.addSql(`alter table "parcels" add constraint "parcels_receiver_id_foreign" foreign key ("receiver_id") references "users" ("id") on update cascade on delete set null;`);
    this.addSql(`alter table "parcels" add constraint "parcels_driver_id_foreign" foreign key ("driver_id") references "drivers" ("id") on update cascade on delete set null;`);

    this.addSql(`alter table "parcel_events" add constraint "parcel_events_parcel_id_foreign" foreign key ("parcel_id") references "parcels" ("id") on update cascade;`);
  }

}
